spring:
  h2:
    console:
      enabled: true
      path: /questions-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:gadget-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
bot:
  accessToken: 4bb11fc1-8f97-4d56-a4d3-21aed7ff552a
